language: go

go:
  - tip

sudo: required

install:
  - go get golang.org/x/net/ipv4
  - go get github.com/udhos/netlink
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/unused/cmd/unused
  - go get honnef.co/go/simple/cmd/gosimple

script:
  - export NHPATH=github.com/udhos/nexthop
  - go install $NHPATH/rib-old
  - go install $NHPATH/rib
  - go install $NHPATH/rip
  - go install $NHPATH/bgp
  - go install $NHPATH/tools/rip-query
  - go test $NHPATH/addr
  - go test $NHPATH/bgp
  - go test $NHPATH/cli
  - go test $NHPATH/command
  - go test $NHPATH/netorder
  - go test $NHPATH/rip
  - sudo GOPATH=$GOPATH /home/travis/.gimme/versions/go/bin/go test $NHPATH/sock
